version: '3.7'
services:
  db:
    container_name: "flock-db"
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: ./api
    container_name: "flock-api"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  view:
    build: ./view
    container_name: "flock-view"
    command: npm run dev
    ports:
      - "8000:8000"
    volumes:
      - ./view/flock_view:/app/nuxt-project/flock-view
    stdin_open: true
    tty: true
    # environment:
    #   - VUE_APP_URL=http://localhost

  text_summary:
    build: ./text_summary
    container_name: "flock-text-summary-es"
    ports:
      - 9000:9000
    volumes: 
      - type: bind
        source: ./text_summary/e_sum
        target: /home/workspace
    tty: true
    
    # FastAPIを9000ポートで待機
    # main.pyのapp = FastAPI()をmain:appと表記する
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000

volumes:
  mysql-data:
    driver: local
